services: # （１）
  server:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      - SAVE_PATH=/save/savedata.json
    restart: always
    volumes:
      - type: bind
        source: "./save"
        target: "/save"
